In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
player_play = pd.read_csv("data/player_play.csv")
game_tracking_2023 = pd.read_csv("data/game_tracking_2023.csv")
combine_results = pd.read_csv("data/combine_results.csv")

# Gather our plays

First we will filter based on if the play included an offensive lineman

Second we will filter out for only passing plays, as we are looking at pass protection

In [11]:
passing = player_play.loc[
    (player_play['lined_up_position'] == 'T') |
    (player_play['lined_up_position'] == 'G') |
    (player_play['lined_up_position'] == 'C'),
    ['game_id', 'play_id', 'nfl_id', 'lined_up_position', 'pass_result']
]

passing = passing[passing['pass_result'].notna()]

In [12]:
passing

           game_id  play_id  nfl_id lined_up_position pass_result
0       2025111610     2279   57183                 T           I
8       2023091801       56   55976                 T          IN
10      2025122701       63   57183                 T           C
16      2023101503     3590   55973                 G           C
21      2026010405     2568   57238                 C           C
...            ...      ...     ...               ...         ...
314167  2025092200      986   57330                 G           R
314172  2025110300     3012   58214                 G           I
314182  2025122811     2539   57207                 G           C
314183  2025081052      373   58211                 T           I
314193  2026011200      150   57172                 C           I

[64114 rows x 5 columns]

# Gather the tracking

For this example we will again be examining Darnell Wright and Paris Johnson Jr.

In [51]:
wright_plays = game_tracking_2023[game_tracking_2023['nfl_id'] == 55874]
paris_plays = game_tracking_2023[game_tracking_2023 ['nfl_id'] == 55870]

In [52]:
wright_weight = combine_results.loc[
    combine_results['nfl_id'] == 55874,
    'combine_weight'
].iloc[0]

paris_weight = combine_results.loc[
    combine_results['nfl_id'] == 55870,
    'combine_weight'
].iloc[0]

In [53]:
wright_plays['force'] = (
    wright_plays['a'] * (wright_weight / 2.20462)
).round(2)

paris_plays['force'] = (
    paris_plays['a'] * (paris_weight / 2.20462)
).round(2)

In [54]:
wright_plays = wright_plays.sort_values(
    ['game_id', 'play_id', 'time']
).copy()

In [55]:
wright_plays['row_num'] = (
    wright_plays.groupby(['game_id', 'play_id']).cumcount()
)

# identify when snap occurs
snap_rows = (
    wright_plays[wright_plays['event'] == 'ball_snap']
    [['game_id', 'play_id', 'row_num']]
    .rename(columns={'row_num': 'snap_row'})
)

wright_plays = wright_plays.merge(
    snap_rows,
    on=['game_id', 'play_id'],
    how='left'
)

In [69]:
wright_snap_3sec = wright_plays[
    wright_plays['row_num'].between(
        wright_plays['snap_row'],
        wright_plays['snap_row'] + 30
    )
].copy()

# Passing

Our focus here is on passing, and in order to find these passing plays we must identify every play where there is a pass

In [78]:
wright_passing = wright_snap_3sec.merge(
    passing[passing['nfl_id'] == 55874],
    on = ['game_id', 'play_id'],
    how = 'left'
)

In [85]:
wright_passing['seconds_after_snap'] = (
    wright_passing['row_num'] - wright_passing['snap_row']
) * 0.1

wright_passing['second'] = np.where(
    wright_passing['seconds_after_snap'] < 1, 1,
    np.where(
        wright_passing['seconds_after_snap'] < 2, 2, 3
    )
)

game_force = (
    wright_passing
    .groupby(['game_id', 'second'])['force']
    .mean()
    .reset_index(name='average_force')
)

game_force

       game_id  second  average_force
0   2023081251       1     208.940143
1   2023081251       2     224.973429
2   2023081251       3     267.587013
3   2023091008       1     227.767770
4   2023091008       2     211.989649
5   2023091008       3     253.165934
6   2023091706       1     221.274385
7   2023091706       2     203.967923
8   2023091706       3     245.093934
9   2023092411       1     216.025902
10  2023092411       2     204.836804
11  2023092411       3     243.279767
12  2023100103       1     211.265225
13  2023100103       2     193.809704
14  2023100103       3     230.112791
15  2023100500       1     138.479016
16  2023100500       2     162.910625
17  2023100500       3     212.956165
18  2023101502       1     214.213636
19  2023101502       2     179.094475
20  2023101502       3     237.973203
21  2023102201       1     202.468591
22  2023102201       2     204.670182
23  2023102201       3     232.004091
24  2023102913       1     243.754545
25  2023102913       2     201.033697
26  2023102913       3     243.954000
27  2023110507       1     232.982471
28  2023110507       2     180.356324
29  2023110507       3     229.754144
30  2023110900       1     210.737167
31  2023110900       2     182.642375
32  2023110900       3     215.321481
33  2023111902       1     229.169640
34  2023111902       2     203.506037
35  2023111902       3     230.999226
36  2023112700       1     198.832721
37  2023112700       2     179.017865
38  2023112700       3     229.283533
39  2023121002       1     245.012629
40  2023121002       2     197.277511
41  2023121002       3     225.606497
42  2023121710       1     231.776458
43  2023121710       2     206.820292
44  2023121710       3     246.598801
45  2023122409       1     218.233391
46  2023122409       2     193.766464
47  2023122409       3     233.136785
48  2023123103       1     228.725216
49  2023123103       2     187.777378
50  2023123103       3     229.449521
51  2024010706       1     237.962426
52  2024010706       2     219.843362
53  2024010706       3     265.870812

### Future updates

1. Need to filter out screen passes as blocking is not a factor here
2. Need to factor out qb_kneel plays as well
3. Shorten plays so that if there is a pass or a sack you stop counting the values